name: tip4
on: push
jobs:
    build-node:
        name: Build and Run Node.js App
        runs-on: ubuntu-latest
        container: node:trixie
        steps:
          - name: Check Node.js and npm Versions
            run: |
              node --version
              npm --version
          - name: Checkout Repository
            uses: actions/checkout@v3
          - name: Install Dependencies
            run: npm install
          - name: Run Application
            run: node app.js    
        
# name: tip3
# on: push
# jobs:
#     build-node:
#         runs-on: ubuntu-latest
#         container: node:trixie
#         steps:
#          - run: node --version
#          - run: npm --version
#          - uses: actions/checkout@v3
#          - run: npm install
#          - run: node app.js






# name: top1andtip2
# on: push
# jobs:
#     build:
#         runs-on: ubuntu-latest
#         container: node:trixie
#         # runs-on: windows-latest
#         steps:
#          - run: node --version
#          - run: npm --version
        
    