name: tip3
on: push
jobs:
    build-node:
        runs-on: ubuntu-latest
        container: node:trixie
        steps:
         - run: node --version
         - run: npm --version
         - uses: actions/checkout@v3
         - run: npm install
         - run: node app.js






# name: top1andtip2
# on: push
# jobs:
#     build:
#         runs-on: ubuntu-latest
#         container: node:trixie
#         # runs-on: windows-latest
#         steps:
#          - run: node --version
#          - run: npm --version
        
    